### ISSUE TITLE
Support VS 2019

### ISSUE THREAD

**Issue by bbenetskyy** [visualmutator/visualmutator#14]
Hi, do you plan to support the newest Visual Studio 2019 ???

**Comment by simondel** [comment]
Hi! I don't think this project is actively maintained anymore. You could check out https://github.com/stryker-mutator/stryker-net which should support most .NET Framework and .NET Core projects. A Visual Studio Code plugin is not yet available, but there is the option to generate an HTML report.

**Comment by bbenetskyy** [comment]
Thank you very much for your reply @simondel I will try **stryker**
