### ISSUE TITLE
Solutions with multiple projects

### ISSUE THREAD

**Issue by josephearl** [visualmutator/visualmutator#7]
I have a solution with 3 projects. One project has code in, one tests and the third some shared code. Visual Mutator  only shows me my third project to mutate and shows no tests.

**Comment by pavzaj** [comment]
What does this version show:
https://github.com/pavzaj/visualmutator/releases/tag/0.0.22
?

**Comment by josephearl** [comment]
@pavzaj thanks for your reply - unfortunately I'm no longer able to test this. I'll close this issue and allow another user to raise if they have a problem with the latest version.
