### ISSUE TITLE
Classes not listed in alphabetic order

### ISSUE THREAD

**Issue by fire-eggs** [visualmutator/visualmutator#8]
Helpful for navigation purposes if classes could be listed in alphabetic order:

![image](https://cloud.githubusercontent.com/assets/9809727/20317954/5043ae94-ab36-11e6-8075-ebe90aefcfc8.png)

**Comment by pavzaj** [comment]
It should be fixed in this version:
https://github.com/pavzaj/visualmutator/releases/tag/0.0.22

**Comment by fire-eggs** [comment]
Thanks, pavzaj - That really helps!

Much obliged,
Kevin

**Comment by pavzaj** [comment]
It this version:
https://github.com/pavzaj/visualmutator/releases/tag/0.0.27
Everything in classes and tests trees should be sorted alphabetically.
